services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2182:2181"    # Changed from 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper  # Persist Zookeeper data

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9092"    # Changed from 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093  # Changed port to 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data  # Persist Kafka logs

  pyspark:
    build: 
      context: .
      dockerfile: Dockerfile.pyspark
    volumes:
      - ./app:/app
      - pyspark_data:/opt/spark/work-dir  # Persist PySpark work directory
    depends_on:
      - kafka


volumes:
  zookeeper_data:
  kafka_data:
  pyspark_data:
